version: '3'

services:

  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_APP_DB}
      - MYSQL_USER=${MYSQL_APP_USER}
      - MYSQL_PASSWORD=${MYSQL_APP_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - prod

  memcached:
    image: memcached:alpine
    container_name: memcached
    entrypoint:
      - memcached
      - -m
      - '256'
    restart: always
    networks:
      - prod

  web:
    build: stayhome/
    container_name: web
    environment:
      - RUNNING_ENV=prod
      - LETSENCRYPT_HOST=www.stayhome.ch,stayhome.ch
      - VIRTUAL_HOST=www.stayhome.ch,stayhome.ch
      - VIRTUAL_PORT=8000
      - MYSQL_APP_DB=${MYSQL_APP_DB}
      - MYSQL_APP_USER=${MYSQL_APP_USER}
      - MYSQL_APP_PASSWORD=${MYSQL_APP_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - SYNC_USER=${SYNC_USER}
      - SYNC_PASSWORD=${SYNC_PASSWORD}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - GOOGLE_UA=${GOOGLE_UA}
    expose:
      - 8000
    depends_on:
      - db
      - memcached
    restart: always
    volumes:
      - api_key:/api
      - datasets:/code/datasets
    networks:
      - prod

volumes:
  db_data:
  api_key:
  datasets:

networks:
  prod:
    external:
      name: infra_prod
