version: '3'

services:

  db:
    build: mariadb/
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=stayhome
      - MYSQL_DATABASE=stayhome
      - MYSQL_USER=stayhome
      - MYSQL_PASSWORD=stayhome
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: stayhome/
    container_name: web
    environment:
      - RUNNING_ENV=dev
      - MYSQL_APP_DB=stayhome
      - MYSQL_APP_USER=stayhome
      - MYSQL_APP_PASSWORD=stayhome
      - DJANGO_SUPERUSER_USERNAME=stayhome
      - DJANGO_SUPERUSER_EMAIL=dev@stayhome.ch
      - DJANGO_SUPERUSER_PASSWORD=stayhome
      - SYNC_USER=sync
      - SYNC_PASSWORD=sync
      - RECAPTCHA_PUBLIC_KEY=""
      - RECAPTCHA_PRIVATE_KEY=""
      - DJANGO_SECRET_KEY=verynotsecretkey
      - GOOGLE_UA=""
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    restart: always
    volumes:
      - api_key:/api

  sync-service:
    build: sync-service/
    container_name: sync-service
    environment:
      - STAYHOME_API_URL=http://web:8000/api
      - SPRING_PROFILES=local
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - web
    restart: always
    volumes:
      - api_key:/api
  
  nodefetch:
    build: nodefetch/
    container_name: nodefetch
    environment:
      - SYNC_SERVICE_BASE_URL=http://sync-service:8080/api/
    depends_on:
      - sync-service
    restart: always

  local-hero:
    build: integrations/localhero/
    container_name: local-hero
    environment:
      - STAYHOME_SYNC_SERVICE_URL=http://sync-service:8080/api/
    depends_on:
      - sync-service
    restart: always

volumes:
  db_data:
  api_key:
