spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  cache:
    type: simple

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
