stayhome:
  sync-service-url: 'http://localhost:8080'
  run-on-start: true
  integrations:
    localhero:
      scrape-cron: ${STAYHOME_INTEGRATIONS_LOCALHERO_SCRAPE_CRON:'* * */6 * * *'}
      target-url: ${STAYHOME_SYNC_SERVICE_URL:'http://sync-service:8080'}
      chunk-size: 50
      page-size: 50
      query-map-class: ch.stayhome.integrations.localhero.infrastructure.feign.querymap.LocalHero
      parallel-threads: 2
      request-ttl: 3d
      sources:
        - key: 'bern'
          providerName: 'bern-local-hero'
          url: 'https://bern.local-hero.ch'
          path: '/wp-json/wp/v2'
          place: 'Bern'
        - key: 'winterthur'
          providerName: 'winterhur-local-hero'
          url: 'https://winterthur.local-hero.ch'
          path: '/wp-json/wp/v2'
          place: 'Winterthur'
        - key: 'solothurn'
          providerName: 'solothurn-local-hero'
          url: 'https://solothurn.local-hero.ch'
          path: '/wp-json/wp/v2'
          place: 'Solothurn'
        - key: 'zug'
          providerName: 'zug-local-hero'
          url: 'https://zug.local-hero.ch'
          path: '/wp-json/wp/v2'
          place: 'Zug'
        - key: 'zuerich'
          providerName: 'zuerich-local-hero'
          url: 'https://zuerich.local-hero.ch'
          path: '/wp-json/wp/v2'
          place: 'Zürich'

spring:
  batch:
    job:
      enabled: ${stayhome.run-on-start}

logging:
  level:
    ROOT: INFO
