stayhome:
  integrations:
    localhero:
      scrape-cron: '*/5 * * * * *'
      source-urls:
        - 'http://localhost:3001'
      target-url: 'http://localhost:8080'
      chunk-size: 1

logging:
  level:
    org.springframework.scheduling: 'DEBUG'
