stayhome:
  integrations:
    localhero:
      scrape-cron: '* * */6 * * *'
      provider-name: 'local-hero.ch'
      restRoute: '/wp-json/wp/v2/posts'
      target-url: 'http://localhost:8080'
      chunk-size: 50
      page-size: 50
      parallel-threads: 2
      request-ttl: 3d
      sources:
        - key: 'bern'
          providerName: 'winterhur-local-hero'
          url: 'https://bern.local-hero.ch'
          place: 'Bern'
        - key: 'winterthur'
          providerName: 'winterhur-local-hero'
          url: 'https://winterthur.local-hero.ch'
          place: 'Winterthur'

spring:
  batch:
    job:
      enabled: false

logging:
  level:
    org.springframework.scheduling: 'DEBUG'
