stayhome:
  integrations:
    localhero:
      scrape-cron: '-'
      target-url: 'http://localhost:8080'

spring:
  batch:
    job:
      enabled: true

logging:
  level:
    org.springframework.scheduling: 'DEBUG'
